### ISSUE TITLE
Demo project and dependencies

### ISSUE THREAD

**Issue by ro-mak** [Mishkun/lobzik#2]
Hi, it was a pleasure to watch your lecture on Mobius. 
I would like to suggest some improvements to your repo.

Try to add a step by step guide how to add your library to a project.
Like that you need 
- classpath org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21
and 
-plugins id(org.jetbrains.kotlin.jvm)
in your buildscript.

And also all modules should apply kotlin plugin.

And a demo app will be great to have to see how it works and to practice using it.

**Comment by Mishkun** [comment]
> Like that you need

> classpath org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21
and
-plugins id(org.jetbrains.kotlin.jvm)
in your buildscript.
And also all modules should apply kotlin plugin.

These were bugs. Any other settings I should clarify with the sample project?

**Comment by ro-mak** [comment]
It seems to me that adding multiple feature modules via featureModulesRegex.add("feature") does nothing, because I can only see one module classes in gephi

Update: I see that you suggest using regex to add multiple modules, but it's not convenient when modules names don't have common parts.

**Comment by ro-mak** [comment]
Also a manual would be great. It is hard to interprete report results without some documentation. 

Update: I see that you have some notes about Lobzik usage in readme, but imagine that you try to explain to a regular developer how to use this lib. 
This manual might include such steps as: 
- right configuration and troubleshooting
- definition of metrics and how to make a decision based on them
- Answer to the question: why report might have zero values? 
- How to interprete Module section
- Why graphics might show nothing?'


Also it would be great to add more details to logs
- add init info like (Lobzik Init Success. Starting to scan the following: Monolith - app, Features - feature1, feature2)
- add some more errors to logs, like: Your configuration is not correct, Lobzik didn't find feature2, consider adding ":" in front of module name)

**Comment by Mishkun** [comment]
Hi @ro-mak! As requested, I wrote an [article](https://dev.to/mishkun/carving-the-path-to-modularity-a-lobzik-tool-case-study-on-the-protonmail-android-app-mid) going step by step into showcasing Lobzik report and how to use it. It also features the sample project based on [fork](https://github.com/Mishkun/proton-mail-android-lobzik-showcase) ProtonMail android client

As for the logs and more clear errors, I would create a separate issue for that.
