### ISSUE TITLE
Missing samples of Lobzik outputs.

### ISSUE THREAD

**Issue by midery** [Mishkun/lobzik#6]
Hi! 

I think that it'll be great to provide some samples of outputs that Lobzik plugin generates for a projects, and how to interpret them.

I haven't seen your Mobius talk, so I'm a little bit confused: description of plugin's API, but I can't understand what profit it could give to me unless I try to apply it to real project. 

I would really appreciate: 
1. If you share a sample of output in README file. If you could also tell us a little bit more about how to read it and how to divide modules - it'll be awesome too.  
2. If you add sample project to this repository which shows monolithic module problem, and which can be used as a playground for plugin. 

Thanks in advance, and thanks for sharing this project!

**Comment by Mishkun** [comment]
Hi @midery! As requested, I wrote an [article](https://dev.to/mishkun/carving-the-path-to-modularity-a-lobzik-tool-case-study-on-the-protonmail-android-app-mid) going step by step into showcasing Lobzik report and how to use it. It also features the sample project based on [fork](https://github.com/Mishkun/proton-mail-android-lobzik-showcase) ProtonMail android client. Hope this will answer your questions. Reopen this issue if there are any of them left. Thank you for your contribution and good luck!
